//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int id { get; set; }
        public string task_name { get; set; }
        public string subject { get; set; }
        public Nullable<int> duration { get; set; }
        public string teacher { get; set; }
        public string @class { get; set; }
        public string keywords { get; set; }
        public string feedbackGiven { get; set; }
    }
}
